import { Inter } from 'next/font/google'
import './globals.css';
import 'bootstrap/dist/css/bootstrap.css';
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
import Row from 'react-bootstrap/Row'
import Container from 'react-bootstrap/Container'
import HeaderMain from './shared/Header';
import FooterMain from './shared/Footer';
import FlatButton from './FlatButton';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The Korean Mall - Korean Cosmetics and Skin Care Products.',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js" async ></script>
      </head>
      <body className={inter.className}>
        <FlatButton/>
        <Container fluid>
          <HeaderMain/>
          {/* <Container> */}
            
              {children}
        
          {/* </Container> */}
          <FooterMain/>
        </Container>
      </body>
    </html>
  )
}
